/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedOnboardingRouteImport } from './routes/_protected/onboarding'
import { Route as ProtectedHelpRouteImport } from './routes/_protected/help'
import { Route as PublicAuthVerifyEmailRouteImport } from './routes/_public/auth/verify-email'
import { Route as PublicAuthResendVerificationRouteImport } from './routes/_public/auth/resend-verification'
import { Route as PublicAuthRegisterSuccessRouteImport } from './routes/_public/auth/register-success'
import { Route as PublicAuthRegisterRouteImport } from './routes/_public/auth/register'
import { Route as PublicAuthLoginRouteImport } from './routes/_public/auth/login'
import { Route as PublicAuthForgotPasswordRouteImport } from './routes/_public/auth/forgot-password'
import { Route as ProtectedTokensSemanticTokensRouteImport } from './routes/_protected/tokens/semantic-tokens'
import { Route as ProtectedTokensPrimitiveTokensRouteImport } from './routes/_protected/tokens/primitive-tokens'
import { Route as ProtectedTokensComponentTokensRouteImport } from './routes/_protected/tokens/component-tokens'
import { Route as ProtectedSettingsWorkspacesRouteImport } from './routes/_protected/settings/workspaces'
import { Route as ProtectedSettingsAccountRouteImport } from './routes/_protected/settings/account'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOnboardingRoute = ProtectedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedHelpRoute = ProtectedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => ProtectedRoute,
} as any)
const PublicAuthVerifyEmailRoute = PublicAuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthResendVerificationRoute =
  PublicAuthResendVerificationRouteImport.update({
    id: '/auth/resend-verification',
    path: '/auth/resend-verification',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicAuthRegisterSuccessRoute =
  PublicAuthRegisterSuccessRouteImport.update({
    id: '/auth/register-success',
    path: '/auth/register-success',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicAuthRegisterRoute = PublicAuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthLoginRoute = PublicAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthForgotPasswordRoute =
  PublicAuthForgotPasswordRouteImport.update({
    id: '/auth/forgot-password',
    path: '/auth/forgot-password',
    getParentRoute: () => PublicRoute,
  } as any)
const ProtectedTokensSemanticTokensRoute =
  ProtectedTokensSemanticTokensRouteImport.update({
    id: '/tokens/semantic-tokens',
    path: '/tokens/semantic-tokens',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedTokensPrimitiveTokensRoute =
  ProtectedTokensPrimitiveTokensRouteImport.update({
    id: '/tokens/primitive-tokens',
    path: '/tokens/primitive-tokens',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedTokensComponentTokensRoute =
  ProtectedTokensComponentTokensRouteImport.update({
    id: '/tokens/component-tokens',
    path: '/tokens/component-tokens',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsWorkspacesRoute =
  ProtectedSettingsWorkspacesRouteImport.update({
    id: '/settings/workspaces',
    path: '/settings/workspaces',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsAccountRoute =
  ProtectedSettingsAccountRouteImport.update({
    id: '/settings/account',
    path: '/settings/account',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/help': typeof ProtectedHelpRoute
  '/onboarding': typeof ProtectedOnboardingRoute
  '/settings/account': typeof ProtectedSettingsAccountRoute
  '/settings/workspaces': typeof ProtectedSettingsWorkspacesRoute
  '/tokens/component-tokens': typeof ProtectedTokensComponentTokensRoute
  '/tokens/primitive-tokens': typeof ProtectedTokensPrimitiveTokensRoute
  '/tokens/semantic-tokens': typeof ProtectedTokensSemanticTokensRoute
  '/auth/forgot-password': typeof PublicAuthForgotPasswordRoute
  '/auth/login': typeof PublicAuthLoginRoute
  '/auth/register': typeof PublicAuthRegisterRoute
  '/auth/register-success': typeof PublicAuthRegisterSuccessRoute
  '/auth/resend-verification': typeof PublicAuthResendVerificationRoute
  '/auth/verify-email': typeof PublicAuthVerifyEmailRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedIndexRoute
  '/help': typeof ProtectedHelpRoute
  '/onboarding': typeof ProtectedOnboardingRoute
  '/settings/account': typeof ProtectedSettingsAccountRoute
  '/settings/workspaces': typeof ProtectedSettingsWorkspacesRoute
  '/tokens/component-tokens': typeof ProtectedTokensComponentTokensRoute
  '/tokens/primitive-tokens': typeof ProtectedTokensPrimitiveTokensRoute
  '/tokens/semantic-tokens': typeof ProtectedTokensSemanticTokensRoute
  '/auth/forgot-password': typeof PublicAuthForgotPasswordRoute
  '/auth/login': typeof PublicAuthLoginRoute
  '/auth/register': typeof PublicAuthRegisterRoute
  '/auth/register-success': typeof PublicAuthRegisterSuccessRoute
  '/auth/resend-verification': typeof PublicAuthResendVerificationRoute
  '/auth/verify-email': typeof PublicAuthVerifyEmailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_protected/help': typeof ProtectedHelpRoute
  '/_protected/onboarding': typeof ProtectedOnboardingRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/settings/account': typeof ProtectedSettingsAccountRoute
  '/_protected/settings/workspaces': typeof ProtectedSettingsWorkspacesRoute
  '/_protected/tokens/component-tokens': typeof ProtectedTokensComponentTokensRoute
  '/_protected/tokens/primitive-tokens': typeof ProtectedTokensPrimitiveTokensRoute
  '/_protected/tokens/semantic-tokens': typeof ProtectedTokensSemanticTokensRoute
  '/_public/auth/forgot-password': typeof PublicAuthForgotPasswordRoute
  '/_public/auth/login': typeof PublicAuthLoginRoute
  '/_public/auth/register': typeof PublicAuthRegisterRoute
  '/_public/auth/register-success': typeof PublicAuthRegisterSuccessRoute
  '/_public/auth/resend-verification': typeof PublicAuthResendVerificationRoute
  '/_public/auth/verify-email': typeof PublicAuthVerifyEmailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/help'
    | '/onboarding'
    | '/settings/account'
    | '/settings/workspaces'
    | '/tokens/component-tokens'
    | '/tokens/primitive-tokens'
    | '/tokens/semantic-tokens'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/register-success'
    | '/auth/resend-verification'
    | '/auth/verify-email'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/help'
    | '/onboarding'
    | '/settings/account'
    | '/settings/workspaces'
    | '/tokens/component-tokens'
    | '/tokens/primitive-tokens'
    | '/tokens/semantic-tokens'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/register-success'
    | '/auth/resend-verification'
    | '/auth/verify-email'
  id:
    | '__root__'
    | '/_protected'
    | '/_public'
    | '/_protected/help'
    | '/_protected/onboarding'
    | '/_protected/'
    | '/_protected/settings/account'
    | '/_protected/settings/workspaces'
    | '/_protected/tokens/component-tokens'
    | '/_protected/tokens/primitive-tokens'
    | '/_protected/tokens/semantic-tokens'
    | '/_public/auth/forgot-password'
    | '/_public/auth/login'
    | '/_public/auth/register'
    | '/_public/auth/register-success'
    | '/_public/auth/resend-verification'
    | '/_public/auth/verify-email'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/onboarding': {
      id: '/_protected/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof ProtectedOnboardingRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/help': {
      id: '/_protected/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof ProtectedHelpRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_public/auth/verify-email': {
      id: '/_public/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof PublicAuthVerifyEmailRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/resend-verification': {
      id: '/_public/auth/resend-verification'
      path: '/auth/resend-verification'
      fullPath: '/auth/resend-verification'
      preLoaderRoute: typeof PublicAuthResendVerificationRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/register-success': {
      id: '/_public/auth/register-success'
      path: '/auth/register-success'
      fullPath: '/auth/register-success'
      preLoaderRoute: typeof PublicAuthRegisterSuccessRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/register': {
      id: '/_public/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof PublicAuthRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/login': {
      id: '/_public/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof PublicAuthLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/forgot-password': {
      id: '/_public/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof PublicAuthForgotPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_protected/tokens/semantic-tokens': {
      id: '/_protected/tokens/semantic-tokens'
      path: '/tokens/semantic-tokens'
      fullPath: '/tokens/semantic-tokens'
      preLoaderRoute: typeof ProtectedTokensSemanticTokensRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/tokens/primitive-tokens': {
      id: '/_protected/tokens/primitive-tokens'
      path: '/tokens/primitive-tokens'
      fullPath: '/tokens/primitive-tokens'
      preLoaderRoute: typeof ProtectedTokensPrimitiveTokensRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/tokens/component-tokens': {
      id: '/_protected/tokens/component-tokens'
      path: '/tokens/component-tokens'
      fullPath: '/tokens/component-tokens'
      preLoaderRoute: typeof ProtectedTokensComponentTokensRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/workspaces': {
      id: '/_protected/settings/workspaces'
      path: '/settings/workspaces'
      fullPath: '/settings/workspaces'
      preLoaderRoute: typeof ProtectedSettingsWorkspacesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/account': {
      id: '/_protected/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof ProtectedSettingsAccountRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedHelpRoute: typeof ProtectedHelpRoute
  ProtectedOnboardingRoute: typeof ProtectedOnboardingRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedSettingsAccountRoute: typeof ProtectedSettingsAccountRoute
  ProtectedSettingsWorkspacesRoute: typeof ProtectedSettingsWorkspacesRoute
  ProtectedTokensComponentTokensRoute: typeof ProtectedTokensComponentTokensRoute
  ProtectedTokensPrimitiveTokensRoute: typeof ProtectedTokensPrimitiveTokensRoute
  ProtectedTokensSemanticTokensRoute: typeof ProtectedTokensSemanticTokensRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedHelpRoute: ProtectedHelpRoute,
  ProtectedOnboardingRoute: ProtectedOnboardingRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedSettingsAccountRoute: ProtectedSettingsAccountRoute,
  ProtectedSettingsWorkspacesRoute: ProtectedSettingsWorkspacesRoute,
  ProtectedTokensComponentTokensRoute: ProtectedTokensComponentTokensRoute,
  ProtectedTokensPrimitiveTokensRoute: ProtectedTokensPrimitiveTokensRoute,
  ProtectedTokensSemanticTokensRoute: ProtectedTokensSemanticTokensRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface PublicRouteChildren {
  PublicAuthForgotPasswordRoute: typeof PublicAuthForgotPasswordRoute
  PublicAuthLoginRoute: typeof PublicAuthLoginRoute
  PublicAuthRegisterRoute: typeof PublicAuthRegisterRoute
  PublicAuthRegisterSuccessRoute: typeof PublicAuthRegisterSuccessRoute
  PublicAuthResendVerificationRoute: typeof PublicAuthResendVerificationRoute
  PublicAuthVerifyEmailRoute: typeof PublicAuthVerifyEmailRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAuthForgotPasswordRoute: PublicAuthForgotPasswordRoute,
  PublicAuthLoginRoute: PublicAuthLoginRoute,
  PublicAuthRegisterRoute: PublicAuthRegisterRoute,
  PublicAuthRegisterSuccessRoute: PublicAuthRegisterSuccessRoute,
  PublicAuthResendVerificationRoute: PublicAuthResendVerificationRoute,
  PublicAuthVerifyEmailRoute: PublicAuthVerifyEmailRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
